---
abstract: 'generate your password'
author:
  - 'Dai Okabayashi <bayashi@cpan.org>'
build_requires:
  File::Temp: 0
  Test::More: 0.88
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-MyPasswd
provides:
  App::MyPasswd:
    file: lib/App/MyPasswd.pm
    version: 0.01
requires:
  Digest::HMAC_SHA1: 0
  Getopt::Long: 2.38
  IO::Stty: 0
  POSIX: 0
  Pod::Usage: 0
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bayashi/App-MyPasswd
version: 0.01
