=encoding utf8


This is Perl module B<App::MyPasswd>.

=begin html

<a href="http://travis-ci.org/bayashi/App-MyPasswd"><img src="https://secure.travis-ci.org/bayashi/App-MyPasswd.png"/></a> <a href="https://coveralls.io/r/bayashi/App-MyPasswd"><img src="https://coveralls.io/repos/bayashi/App-MyPasswd/badge.png?branch=master"/></a>

=end html


=head1 INSTALLATION

App::MyPasswd installation is straightforward. If your CPAN shell is set up,
you should just be able to do

    % cpan App::MyPasswd

Download it, unpack it, then build it as per the usual:

    % perl Makefile.PL
    % make && make test

Then install it:

    % make install


=head1 DOCUMENTATION

App::MyPasswd documentation is available as in POD. So you can do:

    % perldoc App::MyPasswd


=head1 REPOSITORY

App::MyPasswd is hosted on github
L<http://github.com/bayashi/App-MyPasswd>


=head1 LICENSE

This module is free software; you can redistribute it and/or
modify it under the same terms as Perl itself. See L<perlartistic>.


=head1 AUTHOR

Dai Okabayashi E<lt>bayashi@cpan.orgE<gt>
